import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;


/**
 * Created by students UA:FTI-EI De Laet Jan & Yigit Yunus Emre on 17/03/2016.
 */
public class GUI
{

    //Main Pane
    public JPanel mainPanel;
    public JTextField loginText;

    //catalogue Tab
    public JTextArea detailsTextArea;
    public JList specificComponentList;
    public JList userCfgList;
    public JButton calculateButton;
    public JTabbedPane mainTabbedPanel;
    public JTextField searchText;
    //Watt Usage Tab
    public JTextArea wattInfo;
    public JTextArea wattResults;
    public JButton addCompare;
    //Compare Tab
    public JTextArea compareArea1;
    public JTextArea compareArea2;
    public JProgressBar progressBar;

    public JTextArea exportResults;
    //Compatibility Check Tab
    public JTextArea compatibilityInfo;
    public JTextArea compatibilityResults;
    private JButton sortZA;
    private JButton sortAZ;
    private JTextArea welcomeTitle;
    private JTextArea userCfgTitle;
    //public String input;
    private JLabel PCBuilderIcon;
    //Main Tabbed Panes
    private JPanel catalogueTab;
    private JPanel compareTab;
    private JPanel wattTab;
    private JPanel compatibilityTab;
    private JPanel exportTab;
    private JTextArea detailsTitleTextArea;
    private JTextArea specificComponentTitle;
    private JScrollPane specificComponentScrollPane;
    private JButton motherboardButton;
    private JButton CPUButton;
    private JButton RAMButton;
    private JButton GPUButton;
    private JButton PSUButton;
    private JButton drivesButton;
    private JButton addComponent;
    private JButton saveUserCfg;
    private JButton compatibilityButton;
    //Export (offer file) Tab
    private JTextArea exportInfo;
    private JButton exportButton;
    //Error message plane
    private JPanel errorPanel;
    private JOptionPane loginPane;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public GUI()
    {
        JFrame frame = new JFrame("PCBuilder Tool");
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocation(200, 200);
        frame.setVisible(true);

        JPanel panel = new JPanel();

        /*
        loginText.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                input = loginText.getText();
                System.out.println("Login name: " + input);
            }
        });
        */

    }

    public void setLoginActionListener(ActionListener al)
    {
        loginText.addActionListener(al);
    }

    public void setCalculateWattButtonActionListener(ActionListener al)
    {
        calculateButton.addActionListener(al);
    }

    public void setCompatibilityCheckActionListener(ActionListener al)
    {
        compatibilityButton.addActionListener(al);
    }

    public void setExportButtonActionListener(ActionListener al)
    {
        exportButton.addActionListener(al);
    }

    public void setSelectMotherboardActionListener(ActionListener al)
    {
        motherboardButton.addActionListener(al);
    }

    public void setSelectCPUActionListener(ActionListener al)
    {
        CPUButton.addActionListener(al);
    }

    public void setSelectRAMActionListener(ActionListener al)
    {
        RAMButton.addActionListener(al);
    }

    public void setSelectGPUActionListener(ActionListener al)
    {
        GPUButton.addActionListener(al);
    }

    public void setSelectPSUActionListener(ActionListener al)
    {
        PSUButton.addActionListener(al);
    }

    public void setSelectDriveActionListener(ActionListener al)
    {
        drivesButton.addActionListener(al);
    }

    public void setSearchActionListener(ActionListener al)
    {
        searchText.addActionListener(al);
    }

    public void setSortAZActionListener(ActionListener al)
    {
        sortAZ.addActionListener(al);
    }

    public void setSortZAActionListener(ActionListener al)
    {
        sortZA.addActionListener(al);
    }

    // Compare Button in Component Catalogue tab

    public void setAddComponentActionListener(ActionListener al)
    {
        addComponent.addActionListener(al);
    }

    public void setAddToCompareActionListener(ActionListener al)
    {
        addCompare.addActionListener(al);
    }

    public void setSaveUserCfgActionListener(ActionListener al)
    {
        saveUserCfg.addActionListener(al);
    }

    public void setErrorPanel(String error)
    {
        JOptionPane.showMessageDialog(errorPanel, error, "ERROR!", JOptionPane.ERROR_MESSAGE);
    }

    public void setProgressBar()
    {
        switch (PCBuilder.PCBE.myPc.userCfg.size())
        {
            case 1:
                progressBar.setValue(20);
                break;
            case 2:
                progressBar.setValue(40);
                break;
            case 3:
                progressBar.setValue(60);
                break;
            case 4:
                progressBar.setValue(80);
                break;
            case 5:
                progressBar.setValue(100);
                break;
            case 6:
                progressBar.setValue(120);
                break;
        }
    }

    public boolean setLoginVerification()
    {
        int result = JOptionPane.showConfirmDialog(null,
                "User not found. Are you sure you wish to make a new user ?", null, JOptionPane.YES_NO_OPTION);
        return result == JOptionPane.YES_OPTION;
    }

    public void updateWattTab()
    {
        String textComponent = "";
        for (Component component : PCBuilder.PCBE.myPc.userCfg)
        {
            textComponent += "\n" + component.getGroupComponent() + ": " + component.getBrandComponent() + " " + component.getNameComponent() + "\nIndividual Watt Usage: " + component.getWattUsage() + " Watt\n";
        }
        wattInfo.setText(textComponent);
    }

    public void updateCheckCompatibilityTab()
    {
        String textComponent = "Your configuration:\n";
        for (Component component : PCBuilder.PCBE.myPc.userCfg)
        {
            textComponent += "\n" + component.getGroupComponent() + ": " + component.getBrandComponent() + " " + component.getNameComponent();
        }
        compatibilityInfo.setText(textComponent);
    }

    public void updateExportTab()
    {
        String textComponent = "";
        for (Component component : PCBuilder.PCBE.myPc.userCfg)
        {
            textComponent += "\n" + component.getGroupComponent() + ": " + component.getBrandComponent() + " " + component.getNameComponent() + "\n";
        }
        exportInfo.setText(textComponent);
    }

    public boolean setCalcWattVerification()
    {
        int result = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to continue with less than 6 components ?", null, JOptionPane.YES_NO_OPTION);
        return result == JOptionPane.YES_OPTION;
    }

    public boolean setCompCheckVerification()
    {
        int result = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to continue with a configuration that isn't compatible ?", null, JOptionPane.YES_NO_OPTION);
        return result == JOptionPane.YES_OPTION;
    }

    public void updateSpecificComponentList(String searchText)
    {
        ArrayList<Component> tempList = new ArrayList<>();
        int size = PCBuilder.componentNameList.size();
        if (!searchText.equals(""))
        {
            for (int i = 0; i < size; i++)
            {
                for (Component component : PCBuilder.componentList)
                {
                    if ((component.getBrandComponent() + " " + component.getNameComponent()).equals(PCBuilder.componentNameList.get(i)))
                    {
                        tempList.add(component);
                    }
                }
            }

            PCBuilder.componentList.clear();
            for (Component component : tempList)
            {
                PCBuilder.componentList.add(component);
            }
        } else
        {
            PCBuilder.DLM.clear();

            for (Component component : PCBuilder.componentList)
            {
                PCBuilder.DLM.addElement(component.getBrandComponent() + " " + component.getNameComponent());
            }
            specificComponentList.setModel(PCBuilder.DLM);
        }
    }

    public boolean setRemoveComponentVerification()
    {
        int result = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to remove selected component from your configuration ?", null, JOptionPane.YES_NO_OPTION);
        return result == JOptionPane.YES_OPTION;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setEnabled(true);
        mainPanel.setMinimumSize(new Dimension(900, 500));
        mainPanel.setPreferredSize(new Dimension(900, 500));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        loginText = new JTextField();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.ipadx = 200;
        mainPanel.add(loginText, gbc);
        userCfgTitle = new JTextArea();
        userCfgTitle.setEditable(false);
        userCfgTitle.setText("Current PC configuration:");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 20.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(userCfgTitle, gbc);
        mainTabbedPanel = new JTabbedPane();
        mainTabbedPanel.setEnabled(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.gridheight = 4;
        gbc.weightx = 100.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(mainTabbedPanel, gbc);
        catalogueTab = new JPanel();
        catalogueTab.setLayout(new GridBagLayout());
        catalogueTab.setAlignmentY(0.0f);
        catalogueTab.setPreferredSize(new Dimension(800, 500));
        mainTabbedPanel.addTab("Component Catalogue", catalogueTab);
        detailsTextArea = new JTextArea();
        detailsTextArea.setEditable(false);
        detailsTextArea.setMinimumSize(new Dimension(0, 10));
        detailsTextArea.setPreferredSize(new Dimension(0, 10));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.gridwidth = 8;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        catalogueTab.add(detailsTextArea, gbc);
        detailsTitleTextArea = new JTextArea();
        detailsTitleTextArea.setEditable(false);
        detailsTitleTextArea.setText("Details of the selected component:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 5;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        catalogueTab.add(detailsTitleTextArea, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        catalogueTab.add(spacer2, gbc);
        motherboardButton = new JButton();
        motherboardButton.setText("Motherboard");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(motherboardButton, gbc);
        CPUButton = new JButton();
        CPUButton.setText("Processor (CPU)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(CPUButton, gbc);
        RAMButton = new JButton();
        RAMButton.setText("Memory (RAM)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(RAMButton, gbc);
        GPUButton = new JButton();
        GPUButton.setText("Graphics Card (GPU)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(GPUButton, gbc);
        PSUButton = new JButton();
        PSUButton.setText("Power Supply (PSU)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(PSUButton, gbc);
        drivesButton = new JButton();
        drivesButton.setText("Drives");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(drivesButton, gbc);
        specificComponentScrollPane = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 6;
        gbc.gridheight = 6;
        gbc.weightx = 5.0;
        gbc.fill = GridBagConstraints.BOTH;
        catalogueTab.add(specificComponentScrollPane, gbc);
        specificComponentList = new JList();
        specificComponentList.setEnabled(true);
        specificComponentScrollPane.setViewportView(specificComponentList);
        specificComponentTitle = new JTextArea();
        specificComponentTitle.setAlignmentX(1.0f);
        specificComponentTitle.setEditable(false);
        specificComponentTitle.setText("Search:");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(specificComponentTitle, gbc);
        addComponent = new JButton();
        addComponent.setText("Add  to your PC configuration");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(addComponent, gbc);
        searchText = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(searchText, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(spacer3, gbc);
        sortZA = new JButton();
        sortZA.setAlignmentY(0.0f);
        sortZA.setMaximumSize(new Dimension(64, 24));
        sortZA.setMinimumSize(new Dimension(64, 24));
        sortZA.setPreferredSize(new Dimension(64, 24));
        sortZA.setText("Z>A");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        catalogueTab.add(sortZA, gbc);
        sortAZ = new JButton();
        sortAZ.setAlignmentX(0.0f);
        sortAZ.setAlignmentY(0.0f);
        sortAZ.setMaximumSize(new Dimension(53, 24));
        sortAZ.setMinimumSize(new Dimension(53, 24));
        sortAZ.setPreferredSize(new Dimension(64, 24));
        sortAZ.setText("A>Z");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        catalogueTab.add(sortAZ, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 10;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(spacer5, gbc);
        addCompare = new JButton();
        addCompare.setPreferredSize(new Dimension(200, 32));
        addCompare.setText("Add to compare");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 10;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(addCompare, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 10;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        catalogueTab.add(spacer6, gbc);
        compareTab = new JPanel();
        compareTab.setLayout(new GridBagLayout());
        mainTabbedPanel.addTab("Compare", compareTab);
        compareArea1 = new JTextArea();
        compareArea1.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 50.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        compareTab.add(compareArea1, gbc);
        compareArea2 = new JTextArea();
        compareArea2.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 50.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        compareTab.add(compareArea2, gbc);
        wattTab = new JPanel();
        wattTab.setLayout(new GridBagLayout());
        mainTabbedPanel.addTab("Watt Usage", wattTab);
        wattInfo = new JTextArea();
        wattInfo.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        wattTab.add(wattInfo, gbc);
        calculateButton = new JButton();
        calculateButton.setText("Calculate Watt Usage");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        wattTab.add(calculateButton, gbc);
        wattResults = new JTextArea();
        wattResults.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        wattTab.add(wattResults, gbc);
        compatibilityTab = new JPanel();
        compatibilityTab.setLayout(new GridBagLayout());
        mainTabbedPanel.addTab("Compatibility Check", compatibilityTab);
        compatibilityInfo = new JTextArea();
        compatibilityInfo.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        compatibilityTab.add(compatibilityInfo, gbc);
        compatibilityButton = new JButton();
        compatibilityButton.setText("Check for compatibility of all components");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        compatibilityTab.add(compatibilityButton, gbc);
        compatibilityResults = new JTextArea();
        compatibilityResults.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        compatibilityTab.add(compatibilityResults, gbc);
        exportTab = new JPanel();
        exportTab.setLayout(new GridBagLayout());
        mainTabbedPanel.addTab("Export Configuration", exportTab);
        exportInfo = new JTextArea();
        exportInfo.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        exportTab.add(exportInfo, gbc);
        exportButton = new JButton();
        exportButton.setText("Export to text file");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        exportTab.add(exportButton, gbc);
        exportResults = new JTextArea();
        exportResults.setEditable(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        exportTab.add(exportResults, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer7, gbc);
        userCfgList = new JList();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(userCfgList, gbc);
        PCBuilderIcon = new JLabel();
        PCBuilderIcon.setIcon(new ImageIcon(getClass().getResource("/PCBuilderIcon.png")));
        PCBuilderIcon.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(PCBuilderIcon, gbc);
        progressBar = new JProgressBar();
        progressBar.setForeground(new Color(-16655360));
        progressBar.setMaximum(120);
        progressBar.setValue(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(progressBar, gbc);
        saveUserCfg = new JButton();
        saveUserCfg.setText("Save your user configuration");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(saveUserCfg, gbc);
        welcomeTitle = new JTextArea();
        welcomeTitle.setEditable(false);
        welcomeTitle.setText("Welcome to the PCBuilder Tool! Please enter your name here:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(welcomeTitle, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}
